name: 'Build Ballista'
on: 
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: '0.12.0'

jobs: 
  buildballista:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.ref_name != 'main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout Ballista
        uses: actions/checkout@v4
        with:
          repository: apache/datafusion-ballista
          fetch-depth: 1
          ref: refs/tags/0.12.0
    
      - name: Build Ballista
        run: ./dev/build-ballista-docker.sh
      
      - name: Push Ballista
        if: github.ref_name != 'main'
        run: |
            docker tag apache/arrow-ballista-scheduler:0.12.0 yusufali/arrow-ballista-scheduler
            docker tag apache/arrow-ballista-executor:0.12.0 yusufali/arrow-ballista-executor

            docker push yusufali/arrow-ballista-scheduler
            docker push yusufali/arrow-ballista-executor
